# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\javit\Python\Multiplicar\multiplicar.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(70, 190, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 407, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout.addWidget(self.checkBox_10)
        self.titulo = QtWidgets.QLabel(self.centralWidget)
        self.titulo.setGeometry(QtCore.QRect(20, 10, 1571, 111))
        font = QtGui.QFont()
        font.setPointSize(73)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.titulo.setFont(font)
        self.titulo.setTextFormat(QtCore.Qt.PlainText)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.seleccionar = QtWidgets.QLabel(self.centralWidget)
        self.seleccionar.setGeometry(QtCore.QRect(90, 200, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.seleccionar.setFont(font)
        self.seleccionar.setObjectName("seleccionar")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(650, 190, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_2.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_2.addWidget(self.checkBox_15)
        self.seleccionar_2 = QtWidgets.QLabel(self.frame_2)
        self.seleccionar_2.setGeometry(QtCore.QRect(20, 10, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.seleccionar_2.setFont(font)
        self.seleccionar_2.setObjectName("seleccionar_2")
        self.pushButtonSalir = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSalir.setGeometry(QtCore.QRect(1430, 938, 150, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButtonSalir.setFont(font)
        self.pushButtonSalir.setObjectName("pushButtonSalir")
        self.pushButtonReiniciar = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonReiniciar.setGeometry(QtCore.QRect(1430, 870, 150, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButtonReiniciar.setFont(font)
        self.pushButtonReiniciar.setObjectName("pushButtonReiniciar")
        self.pushButtonComprobar = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonComprobar.setEnabled(False)
        self.pushButtonComprobar.setGeometry(QtCore.QRect(770, 738, 301, 60))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButtonComprobar.setFont(font)
        self.pushButtonComprobar.setObjectName("pushButtonComprobar")
        self.pushButtonGenerar = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonGenerar.setEnabled(True)
        self.pushButtonGenerar.setGeometry(QtCore.QRect(770, 670, 301, 60))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButtonGenerar.setFont(font)
        self.pushButtonGenerar.setObjectName("pushButtonGenerar")
        self.labelmultiplicando = QtWidgets.QLabel(self.centralWidget)
        self.labelmultiplicando.setGeometry(QtCore.QRect(250, 360, 431, 191))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelmultiplicando.setFont(font)
        self.labelmultiplicando.setText("")
        self.labelmultiplicando.setTextFormat(QtCore.Qt.RichText)
        self.labelmultiplicando.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelmultiplicando.setObjectName("labelmultiplicando")
        self.labelejercicios = QtWidgets.QLabel(self.centralWidget)
        self.labelejercicios.setGeometry(QtCore.QRect(1339, 210, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelejercicios.setFont(font)
        self.labelejercicios.setTextFormat(QtCore.Qt.RichText)
        self.labelejercicios.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelejercicios.setObjectName("labelejercicios")
        self.labelmultiplicador_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelmultiplicador_2.setGeometry(QtCore.QRect(220, 590, 51, 81))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.labelmultiplicador_2.setFont(font)
        self.labelmultiplicador_2.setTextFormat(QtCore.Qt.RichText)
        self.labelmultiplicador_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelmultiplicador_2.setObjectName("labelmultiplicador_2")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(270, 680, 411, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.labelresultado = QtWidgets.QLabel(self.centralWidget)
        self.labelresultado.setGeometry(QtCore.QRect(230, 840, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelresultado.setFont(font)
        self.labelresultado.setText("")
        self.labelresultado.setTextFormat(QtCore.Qt.RichText)
        self.labelresultado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelresultado.setObjectName("labelresultado")
        self.textEditunidades = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditunidades.setGeometry(QtCore.QRect(620, 690, 90, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditunidades.sizePolicy().hasHeightForWidth())
        self.textEditunidades.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.textEditunidades.setFont(font)
        self.textEditunidades.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textEditunidades.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditunidades.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditunidades.setTabChangesFocus(True)
        self.textEditunidades.setObjectName("textEditunidades")
        self.textEditdecenas = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditdecenas.setGeometry(QtCore.QRect(530, 690, 90, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditdecenas.sizePolicy().hasHeightForWidth())
        self.textEditdecenas.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.textEditdecenas.setFont(font)
        self.textEditdecenas.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textEditdecenas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditdecenas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditdecenas.setTabChangesFocus(True)
        self.textEditdecenas.setObjectName("textEditdecenas")
        self.textEditcentenas = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditcentenas.setGeometry(QtCore.QRect(440, 690, 90, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditcentenas.sizePolicy().hasHeightForWidth())
        self.textEditcentenas.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.textEditcentenas.setFont(font)
        self.textEditcentenas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditcentenas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditcentenas.setTabChangesFocus(True)
        self.textEditcentenas.setObjectName("textEditcentenas")
        self.textEditmillares = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditmillares.setGeometry(QtCore.QRect(350, 690, 90, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditmillares.sizePolicy().hasHeightForWidth())
        self.textEditmillares.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.textEditmillares.setFont(font)
        self.textEditmillares.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditmillares.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditmillares.setTabChangesFocus(True)
        self.textEditmillares.setObjectName("textEditmillares")
        self.textEditdecenasdemillares = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditdecenasdemillares.setGeometry(QtCore.QRect(150, 690, 200, 170))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditdecenasdemillares.sizePolicy().hasHeightForWidth())
        self.textEditdecenasdemillares.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(100)
        self.textEditdecenasdemillares.setFont(font)
        self.textEditdecenasdemillares.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditdecenasdemillares.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditdecenasdemillares.setTabChangesFocus(True)
        self.textEditdecenasdemillares.setObjectName("textEditdecenasdemillares")
        self.textEditllevadas1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditllevadas1.setEnabled(False)
        self.textEditllevadas1.setGeometry(QtCore.QRect(550, 350, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditllevadas1.sizePolicy().hasHeightForWidth())
        self.textEditllevadas1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEditllevadas1.setFont(font)
        self.textEditllevadas1.setLineWidth(0)
        self.textEditllevadas1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas1.setTabChangesFocus(True)
        self.textEditllevadas1.setObjectName("textEditllevadas1")
        self.textEditllevadas2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditllevadas2.setEnabled(False)
        self.textEditllevadas2.setGeometry(QtCore.QRect(480, 350, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditllevadas2.sizePolicy().hasHeightForWidth())
        self.textEditllevadas2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEditllevadas2.setFont(font)
        self.textEditllevadas2.setLineWidth(0)
        self.textEditllevadas2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas2.setTabChangesFocus(True)
        self.textEditllevadas2.setObjectName("textEditllevadas2")
        self.textEditllevadas3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditllevadas3.setEnabled(False)
        self.textEditllevadas3.setGeometry(QtCore.QRect(400, 350, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditllevadas3.sizePolicy().hasHeightForWidth())
        self.textEditllevadas3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEditllevadas3.setFont(font)
        self.textEditllevadas3.setLineWidth(0)
        self.textEditllevadas3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas3.setTabChangesFocus(True)
        self.textEditllevadas3.setObjectName("textEditllevadas3")
        self.textEditllevadas4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEditllevadas4.setEnabled(False)
        self.textEditllevadas4.setGeometry(QtCore.QRect(330, 350, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditllevadas4.sizePolicy().hasHeightForWidth())
        self.textEditllevadas4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEditllevadas4.setFont(font)
        self.textEditllevadas4.setLineWidth(0)
        self.textEditllevadas4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditllevadas4.setTabChangesFocus(True)
        self.textEditllevadas4.setObjectName("textEditllevadas4")
        self.labelbien = QtWidgets.QLabel(self.centralWidget)
        self.labelbien.setGeometry(QtCore.QRect(1339, 260, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelbien.setFont(font)
        self.labelbien.setTextFormat(QtCore.Qt.RichText)
        self.labelbien.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelbien.setObjectName("labelbien")
        self.labelmal = QtWidgets.QLabel(self.centralWidget)
        self.labelmal.setGeometry(QtCore.QRect(1340, 311, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelmal.setFont(font)
        self.labelmal.setTextFormat(QtCore.Qt.RichText)
        self.labelmal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelmal.setObjectName("labelmal")
        self.labelnota = QtWidgets.QLabel(self.centralWidget)
        self.labelnota.setGeometry(QtCore.QRect(1329, 369, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelnota.setFont(font)
        self.labelnota.setText("")
        self.labelnota.setTextFormat(QtCore.Qt.RichText)
        self.labelnota.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelnota.setObjectName("labelnota")
        self.labelejercicios_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelejercicios_2.setGeometry(QtCore.QRect(1090, 210, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelejercicios_2.setFont(font)
        self.labelejercicios_2.setTextFormat(QtCore.Qt.RichText)
        self.labelejercicios_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelejercicios_2.setObjectName("labelejercicios_2")
        self.labelbien_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelbien_2.setGeometry(QtCore.QRect(1180, 260, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelbien_2.setFont(font)
        self.labelbien_2.setTextFormat(QtCore.Qt.RichText)
        self.labelbien_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelbien_2.setObjectName("labelbien_2")
        self.labelmal_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelmal_2.setGeometry(QtCore.QRect(1180, 310, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelmal_2.setFont(font)
        self.labelmal_2.setTextFormat(QtCore.Qt.RichText)
        self.labelmal_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelmal_2.setObjectName("labelmal_2")
        self.labelnota_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelnota_2.setGeometry(QtCore.QRect(1140, 370, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.labelnota_2.setFont(font)
        self.labelnota_2.setTextFormat(QtCore.Qt.RichText)
        self.labelnota_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelnota_2.setObjectName("labelnota_2")
        self.labelmultiplicador = QtWidgets.QLabel(self.centralWidget)
        self.labelmultiplicador.setGeometry(QtCore.QRect(510, 530, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelmultiplicador.setFont(font)
        self.labelmultiplicador.setText("")
        self.labelmultiplicador.setTextFormat(QtCore.Qt.RichText)
        self.labelmultiplicador.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelmultiplicador.setObjectName("labelmultiplicador")
        self.labelresultado_2 = QtWidgets.QLabel(self.centralWidget)
        self.labelresultado_2.setGeometry(QtCore.QRect(810, 850, 301, 141))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelresultado_2.setFont(font)
        self.labelresultado_2.setText("")
        self.labelresultado_2.setTextFormat(QtCore.Qt.RichText)
        self.labelresultado_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelresultado_2.setObjectName("labelresultado_2")
        self.corazon = QtWidgets.QLabel(self.centralWidget)
        self.corazon.setGeometry(QtCore.QRect(1260, 520, 1, 1))
        self.corazon.setText("")
        self.corazon.setPixmap(QtGui.QPixmap("corazon.png"))
        self.corazon.setScaledContents(True)
        self.corazon.setObjectName("corazon")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.checkBox_4)
        MainWindow.setTabOrder(self.checkBox_4, self.checkBox_5)
        MainWindow.setTabOrder(self.checkBox_5, self.checkBox_6)
        MainWindow.setTabOrder(self.checkBox_6, self.checkBox_7)
        MainWindow.setTabOrder(self.checkBox_7, self.checkBox_8)
        MainWindow.setTabOrder(self.checkBox_8, self.checkBox_9)
        MainWindow.setTabOrder(self.checkBox_9, self.checkBox_10)
        MainWindow.setTabOrder(self.checkBox_10, self.checkBox_11)
        MainWindow.setTabOrder(self.checkBox_11, self.checkBox_12)
        MainWindow.setTabOrder(self.checkBox_12, self.checkBox_13)
        MainWindow.setTabOrder(self.checkBox_13, self.checkBox_14)
        MainWindow.setTabOrder(self.checkBox_14, self.checkBox_15)
        MainWindow.setTabOrder(self.checkBox_15, self.pushButtonGenerar)
        MainWindow.setTabOrder(self.pushButtonGenerar, self.pushButtonComprobar)
        MainWindow.setTabOrder(self.pushButtonComprobar, self.textEditunidades)
        MainWindow.setTabOrder(self.textEditunidades, self.textEditllevadas1)
        MainWindow.setTabOrder(self.textEditllevadas1, self.textEditdecenas)
        MainWindow.setTabOrder(self.textEditdecenas, self.textEditllevadas2)
        MainWindow.setTabOrder(self.textEditllevadas2, self.textEditcentenas)
        MainWindow.setTabOrder(self.textEditcentenas, self.textEditllevadas3)
        MainWindow.setTabOrder(self.textEditllevadas3, self.textEditmillares)
        MainWindow.setTabOrder(self.textEditmillares, self.textEditllevadas4)
        MainWindow.setTabOrder(self.textEditllevadas4, self.textEditdecenasdemillares)
        MainWindow.setTabOrder(self.textEditdecenasdemillares, self.pushButtonReiniciar)
        MainWindow.setTabOrder(self.pushButtonReiniciar, self.pushButtonSalir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "1"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_5.setText(_translate("MainWindow", "5"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.checkBox_7.setText(_translate("MainWindow", "7"))
        self.checkBox_8.setText(_translate("MainWindow", "8"))
        self.checkBox_9.setText(_translate("MainWindow", "9"))
        self.checkBox_10.setText(_translate("MainWindow", "10"))
        self.titulo.setText(_translate("MainWindow", "APRENDIENDO A MULTIPLICAR"))
        self.seleccionar.setText(_translate("MainWindow", "Seleccionar tablas de multiplicar"))
        self.checkBox_11.setText(_translate("MainWindow", "1"))
        self.checkBox_12.setText(_translate("MainWindow", "2"))
        self.checkBox_13.setText(_translate("MainWindow", "3"))
        self.checkBox_14.setText(_translate("MainWindow", "4"))
        self.checkBox_15.setText(_translate("MainWindow", "5"))
        self.seleccionar_2.setText(_translate("MainWindow", "Seleccionar cifras de multiplicando"))
        self.pushButtonSalir.setText(_translate("MainWindow", "SALIR"))
        self.pushButtonReiniciar.setText(_translate("MainWindow", "REINICIAR"))
        self.pushButtonComprobar.setText(_translate("MainWindow", "COMPROBAR (F6)"))
        self.pushButtonComprobar.setShortcut(_translate("MainWindow", "F6"))
        self.pushButtonGenerar.setText(_translate("MainWindow", "NUEVA (F5)"))
        self.pushButtonGenerar.setShortcut(_translate("MainWindow", "F5"))
        self.labelejercicios.setText(_translate("MainWindow", "0"))
        self.labelmultiplicador_2.setText(_translate("MainWindow", "X"))
        self.labelbien.setText(_translate("MainWindow", "0"))
        self.labelmal.setText(_translate("MainWindow", "0"))
        self.labelejercicios_2.setText(_translate("MainWindow", "Ejercicios:"))
        self.labelbien_2.setText(_translate("MainWindow", "Bien:"))
        self.labelmal_2.setText(_translate("MainWindow", "Mal:"))
        self.labelnota_2.setText(_translate("MainWindow", "Nota:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
